# Numpy Tutorial

In [4]:
import numpy as np

## Creating Arrays using numpy

In [11]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,3,6],[3,7,4],[2,9,4]])
print("1D Array: ",arr1)
print("2D Array: \n",arr2)

1D Array:  [1 2 3 4 5 6]
2D Array: 
 [[1 3 6]
 [3 7 4]
 [2 9 4]]


## Some attributes of arrays

In [13]:
arr3 = np.array([[34,76,12,93,23,55,70],[34,87,23],[33,88,66,11,99]])
print("Type of array: ",type(arr3))
print("Datatype of the array elements: ",arr3.dtype)
print("Shape of array: ",arr3.shape)
# no. of characters in the array
print("Size of the array: ",arr3.size)
print("Size of each item: ",arr3.itemsize)
print("No. od dimensions: ",arr3.ndim)
# no. of bytes of memory space occupied by the array
print("No. of bytes: ",arr3.nbytes)

Type of array:  <class 'numpy.ndarray'>
Datatype of the array elements:  object
Shape of array:  (3,)
Size of the array:  3
Size of each item:  8
No. od dimensions:  1
No. of bytes:  24


## Some special array declaration format and manipulations

In [17]:
# Row-Major (C-style) and Column-Major(Fortran-style) order
arr4 = np.ndarray(shape=(2,2), dtype=float, order='F')
arr4 # random

array([[5.e-324, 5.e-324],
       [0.e+000, 0.e+000]])

In [32]:
arr5 = np.ndarray((4,3), buffer=np.array([2,6,9,1,7,2,3,5,6,1,2,3,4,5,7,4,6]), offset=np.int_().itemsize, dtype=int)
arr5 # offset = 1*itemsize, i.e. skip first element

array([[6, 9, 1],
       [7, 2, 3],
       [5, 6, 1],
       [2, 3, 4]])

In [34]:
arr5.T # the transposed array

array([[6, 7, 5, 2],
       [9, 2, 6, 3],
       [1, 3, 1, 4]])

In [36]:
arr5.data # data -> Python buffer object pointing to the start of the array's data

In [39]:
arr5.flags # flags -> displays the information of the memory layout of the array
# the different labels displayed below are nothing but flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [40]:
arr5.flat # flat -> a 1-D iterator over the array

In [42]:
arr5.imag # imag -> the imaginary part of the array

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [43]:
arr5.real # real -> the real part of the array

array([[6, 9, 1],
       [7, 2, 3],
       [5, 6, 1],
       [2, 3, 4]])

In [45]:
arr5.strides # strides -> tuple of bytes to step in each direction while traversing an array

(12, 4)

## Creating special arrays

In [92]:
x = np.zeros(5)
print("np.zeros(5): ",x)
x = np.zeros((3,4), dtype=int)
print("\n","np.zeros((3,4):","\n",x)
# custom type
x = np.zeros((2,3), dtype=[('x','i4'),('y','i4')])
print("\n",x)
x = np.ones((3,4), dtype=float)
print("\n","np.ones((3,4), dtype=float):","\n",x)
# np.empty((x,y)) is different from np.zeros((x,y)) in the sense that it involves randomization & garbage values
arr = np.empty((4,6))
print("\n","np.empty((3,4)): ",arr)
# identity matrix
arr = np.eye(3,3)
print("\n","Identity matrix: ","\n",arr)
# random array
arr = np.random.rand(4,3)
print("\n","Random array: ","\n",arr)
# random integer array
arr = np.random.randint(7, size=(3,4))
print("\n","Random integer array: ","\n",arr)

np.zeros(5):  [0. 0. 0. 0. 0.]

 np.zeros((3,4): 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

 [[(0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0)]]

 np.ones((3,4), dtype=float): 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 np.empty((3,4)):  [[9.76329770e-312 7.90505033e-322 0.00000000e+000 0.00000000e+000
  1.89146896e-307 1.16095484e-028]
 [2.17230256e-153 1.96097649e+243 4.24819624e+180 1.05016932e-153
  1.06442679e+223 1.03063392e-113]
 [7.98691959e-072 1.47210311e-052 3.42703236e-062 2.24749570e-057
  2.64512447e+185 5.28609935e-085]
 [4.50909741e+198 8.04430783e-095 8.78959876e+198 1.96099265e+243
  6.48224638e+170 3.67145870e+228]]

 Identity matrix:  
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Random array:  
 [[0.22583062 0.54397734 0.19697992]
 [0.70135781 0.77120282 0.08848229]
 [0.45378258 0.19396909 0.9403072 ]
 [0.92091643 0.33153189 0.29674678]]

 Random integer array:  
 [[0 6 2 6]
 [5 4 0 6]
 [0 1 6 3]]


## Array from existing data 

In [95]:
# ndarray from a list
x = [2,6,9,1]
a = np.asarray(x)
print(a)
# ndarray from a tuple
x = (2,8,4,7,0,19)
a = np.asarray(x)
print(a, " a[1]=",a[1])
# ndarray from list of tuples
x = [(2,7,6),(3,5),(4,4,4)]
a = np.asarray(x)
print(a)
# ndarray from a set
x = {2,'hello',456,'world'}
a = np.asarray(x)
print(a)

# the following example demonstrates the use of frombuffer function
s = b'hello world'
a = np.frombuffer(s, dtype='S1', count=5, offset=1)
print(a)

# the 'iter' method builds a list from an iterable object and  
# 'fromiter' can be used to convert the iterface to an array for further display
lst = range(10)
x = iter(lst)
a = np.fromiter(x, dtype=float)
print(a)

# creating arrays from arange()
arr = np.arange(1,13,2)
print(arr)

# creating arrays with linspace
arr = np.linspace(2,10,52)
print(arr)

[2 6 9 1]
[ 2  8  4  7  0 19]  a[1]= 8
[(2, 7, 6) (3, 5) (4, 4, 4)]
{456, 2, 'world', 'hello'}
[b'e' b'l' b'l' b'o' b' ']
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 1  3  5  7  9 11]
[ 2.          2.15686275  2.31372549  2.47058824  2.62745098  2.78431373
  2.94117647  3.09803922  3.25490196  3.41176471  3.56862745  3.7254902
  3.88235294  4.03921569  4.19607843  4.35294118  4.50980392  4.66666667
  4.82352941  4.98039216  5.1372549   5.29411765  5.45098039  5.60784314
  5.76470588  5.92156863  6.07843137  6.23529412  6.39215686  6.54901961
  6.70588235  6.8627451   7.01960784  7.17647059  7.33333333  7.49019608
  7.64705882  7.80392157  7.96078431  8.11764706  8.2745098   8.43137255
  8.58823529  8.74509804  8.90196078  9.05882353  9.21568627  9.37254902
  9.52941176  9.68627451  9.84313725 10.        ]


## Slicing in arrays 

In [108]:
arr7 = np.array([2,78,34,19,33,76,23,2,9,44,83])
print("arr7: ",arr7)
arr8 = arr7[6:9]
print("arr[6:9]: ",arr8)
arr8[0] = 69
# print arr7 after doing the above modification
# always remember: Numpy slicing creates a view of the org. array
print("arr7 after indirect modification: ",arr7)

# Slicing in 2D Arrays
x = [[2,6,9,6],
    [3,87,3,19],
    [3,8,99,21],
    [45,87,21,63]]
arr9 = np.asarray(x)
print("\n",arr9)
print("\n","arr9[1:3,1:3]: ","\n",arr9[1:3,1:3])
print("\n","Column 2: ","\n",arr9[:,1])
print("\n","Row 2: ","\n",arr9[1,:])
print("\n","All elements: ","\n",arr9[:,:])
print("\n","Strides: ","\n",arr9[0::2,1:3])

arr7:  [ 2 78 34 19 33 76 23  2  9 44 83]
arr[6:9]:  [23  2  9]
arr7 after indirect modification:  [ 2 78 34 19 33 76 69  2  9 44 83]

 [[ 2  6  9  6]
 [ 3 87  3 19]
 [ 3  8 99 21]
 [45 87 21 63]]

 arr9[1:3,1:3]:  
 [[87  3]
 [ 8 99]]

 Column 2:  
 [ 6 87  8 87]

 Row 2:  
 [ 3 87  3 19]

 All elements:  
 [[ 2  6  9  6]
 [ 3 87  3 19]
 [ 3  8 99 21]
 [45 87 21 63]]

 Strides:  
 [[ 6  9]
 [ 8 99]]


## More functions on Numpy

In [122]:
arr10 = [[20,2,3],
        [4,9,1]]
arr11 = np.asarray(arr10)
# axis=0 means row-wise
print("arr11.sum(axis=0): ",arr11.sum(axis=0))
# axis=1 means column-wise
print("arr11.sum(axis=1): ",arr11.sum(axis=1))
# sorting is by default done as axis=1
print("Row-wise sorting on arr11:\n",np.sort(arr11))
# sorting can be done Column-wise by writing axis=0
print("Column-wise sorting on arr11:\n",np.sort(arr11, axis=0))

arr12 = np.asarray([[2,8,5],[3,7,0]])
arr13 = arr12.transpose()
print("Transpose of arr12:\n",arr13)
# let's do dot product of arr11 and arr13
# Dot product can only be done if n(col1)=n(row2)
print("Dot pdt. of arr11 and arr13:\n",arr11.dot(arr13))
# let's print the cross product of arr11 and arr12
print("Cross pdt. of arr11 and arr12:\n",np.cross(arr11,arr12))

arr11.sum(axis=0):  [24 11  4]
arr11.sum(axis=1):  [25 14]
Row-wise sorting on arr11:
 [[ 2  3 20]
 [ 1  4  9]]
Column-wise sorting on arr11:
 [[ 4  2  1]
 [20  9  3]]
Our random array:
 [[ 274 1673   66 ...  170  336   78]
 [1599  388   45 ... 1382  108 1008]
 [1172  246 1403 ...  224  276 1746]
 ...
 [ 904 1418 1710 ...  298  658  204]
 [ 278  690  385 ... 1457  287  558]
 [1542 1155  673 ...  342 1243  947]]
Transpose of arr12:
 [[2 3]
 [8 7]
 [5 0]]
Dot pdt. of arr11 and arr13:
 [[71 74]
 [85 75]]
Cross pdt. of arr11 and arr12:
 [[-14 -94 156]
 [ -7   3   1]]


## Know all the Numpy functions! 

In [115]:
# dir(np)

## Analyzing time-complexity for different kinds of sorting on 2D Arrays 

In [148]:
# time-complexity comparison in different sorting techniques when applied on large arrays
a = np.random.randint(17535, size=(10000,1000))
# a = [[2,4,8],[3,1,98],[54,2,8]]
print("Our random array:\n",a)
# DANGEROUS: do it at your own risk!
# %time
# np.sort(a, axis=0, kind='quicksort')
%time
np.sort(a, axis=0, kind='mergesort')
# %time
# np.sort(a, axis=0, kind='heapsort')

Our random array:
 [[ 5482 13601   900 ... 16496 10397 14587]
 [11890 10481 13598 ...  9115  5847  7497]
 [ 7818  3925  8534 ...  2044  2359  1180]
 ...
 [  374  6117  7919 ...  7993  3425 15917]
 [10604  1641 12056 ...  4663 15723  8674]
 [10807 16781  9347 ... 15920 16373  3542]]
Wall time: 0 ns


array([[    0,     0,     1, ...,     3,     2,     1],
       [    3,     1,     2, ...,     5,     4,     2],
       [    4,     2,     5, ...,     6,     6,     5],
       ...,
       [17530, 17531, 17533, ..., 17530, 17531, 17530],
       [17531, 17531, 17533, ..., 17530, 17532, 17533],
       [17532, 17531, 17534, ..., 17534, 17534, 17534]])

## More on Numpy... 

In [151]:
# reshape() function
arr14 = np.array([2,98,43,1,7,3,87,10,44,34,12,98,90,23,56,87,12,23])
# arr14 = arr14.reshape((6,3))
arr14

array([[ 2, 98, 43],
       [ 1,  7,  3],
       [87, 10, 44],
       [34, 12, 98],
       [90, 23, 56],
       [87, 12, 23]])

In [156]:
# argsort() function in numpy
# this function shows the corresponding indexes of the elements in the org. array after they are fully sorted
arr14 = np.array([2,98,43,1,7,3,87,10,44,34,12,98,90,23,56,87,12,23])
print(np.argsort(arr14))
# argmin() gives the first element of the argsort() created array
print(np.argmin(arr14))
# argmax() gives the last element of the argsort() created array
print(np.argmax(arr14))

[ 3  0  5  4  7 10 16 13 17  9  2  8 14 15  6 12 11  1]
3
1


In [164]:
# argsort(), argmin(), argmax() for 2D arrays
arr14 = np.array([2,98,43,1,7,3,87,10,44,34,12,98,90,23,56,87,12,23])
arr15 = arr14.reshape((6,3))
print("arr15: \n",arr15)
print("\n")
print("arr15.argsort():\n",arr15.argsort(axis=0)) #column-wise
print("\n")
print("arr15.argsort():\n",arr15.argsort(axis=1)) #row-wise
print("\n")
print("arr15.argmin():\n",arr15.argmin())
print("\n")
print("arr15.argmax():\n",arr15.argmax())

arr15: 
 [[ 2 98 43]
 [ 1  7  3]
 [87 10 44]
 [34 12 98]
 [90 23 56]
 [87 12 23]]


arr15.argsort():
 [[1 1 1]
 [0 2 5]
 [3 3 0]
 [2 5 2]
 [5 4 4]
 [4 0 3]]


arr15.argsort():
 [[0 2 1]
 [0 2 1]
 [1 2 0]
 [1 0 2]
 [1 2 0]
 [1 2 0]]


arr15.argmin():
 3


arr15.argmax():
 1


## Masking - Important concept in Image processing 

In [165]:
arr11 = np.array([1,2,3,4,5,6,7,8,9])
mask = np.array([0,1,1,0,1,0,1,0,0],dtype=bool)
print(arr11[mask])

[2 3 5 7]


## Yet some more methods...

In [166]:
arr16 = np.array([[1,2,3,4,5],[6,7,8,9,9]])
print(arr16)
print("Sum :\t",np.sum(arr16))
print("Sum :\t",np.sum(arr16,axis=0))
print("Prod :\t",np.prod(arr16))
print("Prod :\t",np.prod(arr16,axis=0))
print("Minimum :\t",np.min(arr16,axis=0))
print("Maximum :\t",np.max(arr16,axis=0))
print("Mean :\t",np.mean(arr16,axis=0))
print("Variance:\t",np.var(arr16,axis=0))
print("Standard Deviation:\t",np.std(arr16,axis=0))
print("Average:\t",np.average(arr16,axis=0))
print("Weighted Average:\t",np.average(arr16,weights=[1,2,3,4,5],axis=1))

[[1 2 3 4 5]
 [6 7 8 9 9]]
Sum :	 54
Sum :	 [ 7  9 11 13 14]
Prod :	 3265920
Prod :	 [ 6 14 24 36 45]
Minimum :	 [1 2 3 4 5]
Maximum :	 [6 7 8 9 9]
Mean :	 [3.5 4.5 5.5 6.5 7. ]
Variance:	 [6.25 6.25 6.25 6.25 4.  ]
Standard Deviation:	 [2.5 2.5 2.5 2.5 2. ]
Average:	 [3.5 4.5 5.5 6.5 7. ]
Weighted Average:	 [3.66666667 8.33333333]


## Scalar Operations - Arithmetic 

In [167]:
arr17 = np.array([1,2,3])
arr18 = np.array([4,5,6])
arr19 = arr17+arr18
arr20 = arr17 - arr18
print("Summation:\t",arr19)
print("Difference:\t",arr20)
arr20+=5
print("Previous output after adding 5:",arr20)

Summation:	 [5 7 9]
Difference:	 [-3 -3 -3]
Previous output after adding 5: [2 2 2]


## Relational Operations

In [168]:
result1 = arr17 == arr18
print(result1)

[False False False]


## Trignometric & Logarithmic operations 

In [169]:
arr21 = np.array([15,30,45,90])
result2 = np.sin(arr21)
print("Sin values:\t",result2)
result3 = np.log(arr21)
print("Log value:\t",result3)

Sin values:	 [ 0.65028784 -0.98803162  0.85090352  0.89399666]
Log value:	 [2.7080502  3.40119738 3.80666249 4.49980967]


## Vector operations

### Math - Scalar and Vector

#### Scalar

* np.add(a,1) -> Add 1 to each array element
* np.subtract(a,2) -> Subtract 2 from each array element
* np.multiply(a,3) -> Multiply each array element by 3
* np.divide(a,4) -> Divide each array element by 4 (it returns np.nan for division by zero)
* np.power(a,5) -> Raise each array element to the 5th power

#### Vector Math

* np.add(a1,a2) -> Elementwise add a2 to a1
* np.subtract(a1,a2) -> Elementwise subtract a2 from a1
* np.multiply(a1,a2) -> Elementwise multiply a1 by a2
* np.divide(a1,a2) -> Elementwise divide a1 by a2
* np.power(a1,a2) -> Elementwise raise a1 raised to the power of a2

* np.array_equal(a1,a2) -> Returns True if the arrays have the same elements and shape *(Note - a1 == a2 -> Returns True if the arrays have the same elements)*
* np.sqrt(a) -> Square root of each element in the array
* np.round(a) -> Rounds to the nearest int